version: "3.8"

services:
  app:
    container_name: sso-idp-attech-jenkins
    image: sso-idp-attech-jenkins
    build:
      context: .
    volumes:
      - .:/app:rw
    ports:
      - "80:80"
    command: >
      sh -c "python3 main.py -e prod"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - fullstack
    depends_on:
      - db_idp
  db_idp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faisal
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432
    networks:
      - fullstack
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container1
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres
  #     PGADMIN_DEFAULT_PASSWORD: faisal
  #   depends_on:
  #     - db_idp
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - fullstack
  #   restart: unless-stopped
volumes:
    postgres_data:
                
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge