version: "3.8"

services:
  db_idp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faisal
      - POSTGRES_DB=sso_idp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
    volumes:
      - .:/app:rw
    ports:
      - "3000:3000"
    command:
      sh -c "python3 main.py -e prod"
    depends_on:
      - db_idp
      - redis

  redis:
    image: "redis:alpine"
    ports:
     - 6379:6379
    volumes:
      - redis_data:/data

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery worker -A celery_worker.celery --loglevel=INFO -P eventlet
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://:Attech123@18.134.217.103:6379/0
      - CELERY_RESULT_BACKEND=redis://:Attech123@18.134.217.103:6379/0
    depends_on:
      - app
      - redis

volumes:
  postgres_data:
  redis_data:
