version: "3.8"

services:
  app:
    container_name: sso-idp
    image: sso-idp
    build:
      context: .
    
    volumes:
      - .:/app:rw
    ports:
      - "8080:8080"
    command: >
      sh -c "python3 app.py"
    env_file:
      - .env
    restart: on-failure