version: "3.8"

services:
  db_idp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faisal
      - POSTGRES_DB=sso_idp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
    volumes:
      - .:/app:rw
    ports:
      - "80:80"
    command: >
      sh -c "python3 main.py -e prod"
    depends_on:
      - db_idp
      - redis

  redis:
    image: "redis:alpine"
    ports:
     - 6379:6379
volumes:
    postgres_data:
                