"""verification elements added

Revision ID: 0ddf36570065
Revises: b1ee1c9c729b
Create Date: 2022-07-06 13:16:55.666629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddf36570065'
down_revision = 'b1ee1c9c729b'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('idp_users', sa.Column('verification_id', sa.String(length=255), nullable=False))
    # op.add_column('idp_users', sa.Column('verification_time_tag', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idp_users', 'verification_time_tag')
    op.drop_column('idp_users', 'verification_id')
    # ### end Alembic commands ###
