"""empty message

Revision ID: 12472f5130b9
Revises: c2b668e63cff
Create Date: 2022-06-07 14:17:32.910550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12472f5130b9'
down_revision = 'c2b668e63cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
