"""verification elements added

Revision ID: 1cb8f382ebe3
Revises: 0ddf36570065
Create Date: 2022-07-06 13:19:40.553072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb8f382ebe3'
down_revision = '0ddf36570065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idp_users', sa.Column('verification_id', sa.String(length=255), nullable=True))
    op.add_column('idp_users', sa.Column('verification_time_tag', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idp_users', 'verification_time_tag')
    op.drop_column('idp_users', 'verification_id')
    # ### end Alembic commands ###
