"""empty message

Revision ID: 1f7b1cd17c27
Revises: c6a1e0b17f22
Create Date: 2022-06-06 00:44:09.458744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7b1cd17c27'
down_revision = 'c6a1e0b17f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
