"""running migrations for idp column

Revision ID: 416a1d6ed7b2
Revises: 4aee501c27fb
Create Date: 2022-07-24 20:10:53.452903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416a1d6ed7b2'
down_revision = '4aee501c27fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idp_users', sa.Column('verification_id', sa.String(length=255), nullable=True))
    op.add_column('idp_users', sa.Column('verification_time_tag', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idp_users', 'verification_time_tag')
    op.drop_column('idp_users', 'verification_id')
    # ### end Alembic commands ###
