"""added column in api table

Revision ID: 4415c8582402
Revises: 8f18d95ff0b4
Create Date: 2022-07-14 23:17:48.318561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4415c8582402'
down_revision = '8f18d95ff0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('api', sa.Column('method', sa.String(length=255), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api', 'method')
    # ### end Alembic commands ###
