"""empty message

Revision ID: 45647fc3afd4
Revises: af87f2dc4440
Create Date: 2022-05-23 18:11:44.761910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45647fc3afd4'
down_revision = 'af87f2dc4440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
