"""empty message

Revision ID: 50504d8cf311
Revises: 1f7b1cd17c27
Create Date: 2022-06-06 13:40:49.602435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50504d8cf311'
down_revision = '1f7b1cd17c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('roles', sa.Column('user_type_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'roles', 'idp_user_types', ['user_type_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_type_id')
    # ### end Alembic commands ###
