"""changes in roles column

Revision ID: 61d0f23275fe
Revises: d3252013c120
Create Date: 2022-06-10 18:11:46.632328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d0f23275fe'
down_revision = 'd3252013c120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('type_role_permissions', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('sp_apps_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'type_role_permissions', ['type_role_permissions'], ['id'])
    op.create_foreign_key(None, 'roles', 'sp_apps', ['sp_apps_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'sp_apps_id')
    op.drop_column('roles', 'type_role_permissions')
    # ### end Alembic commands ###
