"""empty message

Revision ID: 6f44d8a402ac
Revises: 8618622e6dc6
Create Date: 2022-05-20 05:06:37.090949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f44d8a402ac'
down_revision = '8618622e6dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
