"""changing driq_practice_role table deleting role_id column

Revision ID: 8078a9ff508f
Revises: 3c14414858ca
Create Date: 2022-06-14 18:29:53.635017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8078a9ff508f'
down_revision = '3c14414858ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('driq_practices_role_role_id_fkey', 'driq_practices_role', type_='foreignkey')
    op.drop_column('driq_practices_role', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driq_practices_role', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('driq_practices_role_role_id_fkey', 'driq_practices_role', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
