"""empty message

Revision ID: 83176c8ffdd2
Revises: 1e4ab2c0a2ef
Create Date: 2022-06-04 17:22:07.694245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83176c8ffdd2'
down_revision = '1e4ab2c0a2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('idp_users', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.alter_column('idp_users', 'other_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('idp_users', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('idp_users', 'contact_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('idp_users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('idp_users', 'last_login_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'idp_users', 'idp_user_types', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idp_users', type_='foreignkey')
    op.alter_column('idp_users', 'last_login_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('idp_users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('idp_users', 'contact_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('idp_users', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('idp_users', 'other_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('idp_users', 'user_type_id')
    # ### end Alembic commands ###
