"""added column app_name in user_action_model

Revision ID: 842e366cac94
Revises: f056438b0c5f
Create Date: 2022-07-16 01:45:45.341966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842e366cac94'
down_revision = 'f056438b0c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_action', sa.Column('app_name', sa.String(length=155), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_action', 'app_name')
    # ### end Alembic commands ###
