"""empty message

Revision ID: 8618622e6dc6
Revises: ae782b80ae28
Create Date: 2022-05-20 03:38:41.385669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8618622e6dc6'
down_revision = 'ae782b80ae28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
