"""updated column in user action table

Revision ID: 8f18d95ff0b4
Revises: 3a9a2e427b67
Create Date: 2022-07-14 17:00:20.713048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f18d95ff0b4'
down_revision = '3a9a2e427b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_action', sa.Column('role_name', sa.String(length=155), nullable=False))
    # op.drop_constraint('user_action_role_id_fkey', 'user_action', type_='foreignkey')
    # op.create_foreign_key(None, 'user_action', 'action', ['action_id'], ['id'])
    # op.drop_column('user_action', 'role_id')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_action', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_action', type_='foreignkey')
    op.create_foreign_key('user_action_role_id_fkey', 'user_action', 'roles', ['role_id'], ['id'])
    op.drop_column('user_action', 'role_name')
    # ### end Alembic commands ###
