"""empty message

Revision ID: 98438d8244d6
Revises: 6f44d8a402ac
Create Date: 2022-05-23 18:04:57.965857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98438d8244d6'
down_revision = '6f44d8a402ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
