"""gender column change

Revision ID: 9e3d49200697
Revises: c6d1a9676aab
Create Date: 2022-06-16 23:53:49.790680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3d49200697'
down_revision = 'c6d1a9676aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('gender', sa.Column('name', sa.String(length=255), nullable=False))
    # op.drop_column('gender', 'gender')
    op.create_foreign_key(None, 'sp_apps_role_driq_practice_role', 'sp_apps_role', ['sp_apps_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sp_apps_role_driq_practice_role', type_='foreignkey')
    op.add_column('gender', sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('gender', 'name')
    # ### end Alembic commands ###
