"""empty message

Revision ID: a0295abdf307
Revises: 83176c8ffdd2
Create Date: 2022-06-04 20:38:31.160221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0295abdf307'
down_revision = '83176c8ffdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idp_users_organization_id_key', 'idp_users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idp_users_organization_id_key', 'idp_users', ['organization_id'])
    # ### end Alembic commands ###
