"""empty message

Revision ID: ae782b80ae28
Revises: e668cbd18339
Create Date: 2022-05-18 16:36:50.001308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae782b80ae28'
down_revision = 'e668cbd18339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('service_providers', sa.Column('sp_name', sa.String(length=100), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers', 'sp_name')
    # ### end Alembic commands ###
