"""empty message

Revision ID: af87f2dc4440
Revises: 98438d8244d6
Create Date: 2022-05-23 18:10:14.490439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af87f2dc4440'
down_revision = '98438d8244d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
