"""empty message

Revision ID: bc2afcacf593
Revises: db66c8df21c6
Create Date: 2022-06-07 14:11:09.827043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2afcacf593'
down_revision = 'db66c8df21c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
