"""empty message

Revision ID: bfc30f0e2f31
Revises: 45647fc3afd4
Create Date: 2022-05-25 15:23:21.638228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc30f0e2f31'
down_revision = '45647fc3afd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('saml_users_session_saml_req_key', 'saml_users_session', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('saml_users_session_saml_req_key', 'saml_users_session', ['saml_req'])
    # ### end Alembic commands ###
