"""empty message

Revision ID: c2b668e63cff
Revises: bc2afcacf593
Create Date: 2022-06-07 14:15:41.105396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b668e63cff'
down_revision = 'bc2afcacf593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
