"""empty message

Revision ID: c6a1e0b17f22
Revises: 7c6bbc42f715
Create Date: 2022-06-05 18:18:36.981415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a1e0b17f22'
down_revision = '7c6bbc42f715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sp_apps', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('sp_apps', sa.Column('inactive_logo_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'sp_apps', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sp_apps', type_='unique')
    op.drop_column('sp_apps', 'inactive_logo_url')
    op.drop_column('sp_apps', 'display_name')
    # ### end Alembic commands ###
