"""changing sp_apps_role_model

Revision ID: c6d1a9676aab
Revises: 8078a9ff508f
Create Date: 2022-06-15 19:54:07.641376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d1a9676aab'
down_revision = '8078a9ff508f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('sp_apps_role', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('sp_apps_role', 'sp_apps_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('sp_apps_role', 'roles_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sp_apps_role', 'roles_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sp_apps_role', 'sp_apps_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sp_apps_role', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
