"""First commit

Revision ID: ccfdf6e1d40a
Revises: d5d74df8722d
Create Date: 2022-06-07 14:30:32.650138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfdf6e1d40a'
down_revision = 'd5d74df8722d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
