"""creating relation idp user with gender 

Revision ID: d1eef53fe6c7
Revises: 81d3d30259c5
Create Date: 2022-06-14 00:37:45.822452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1eef53fe6c7'
down_revision = '81d3d30259c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('idp_users', sa.Column('dr_iq_gender_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'idp_users', 'gender', ['dr_iq_gender_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idp_users', type_='foreignkey')
    op.drop_column('idp_users', 'dr_iq_gender_id')
    # ### end Alembic commands ###
