"""empty message

Revision ID: d5d74df8722d
Revises: 12472f5130b9
Create Date: 2022-06-07 14:18:38.037639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d74df8722d'
down_revision = '12472f5130b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
