"""empty message

Revision ID: db66c8df21c6
Revises: 50504d8cf311
Create Date: 2022-06-07 13:23:03.705177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db66c8df21c6'
down_revision = '50504d8cf311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_saml_users_session_id', table_name='saml_users_session')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_saml_users_session_id', 'saml_users_session', ['id'], unique=False)
    # ### end Alembic commands ###
