"""added column level in action table and deleted column in user action table

Revision ID: f056438b0c5f
Revises: 4415c8582402
Create Date: 2022-07-15 15:40:17.798391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f056438b0c5f'
down_revision = '4415c8582402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('action', sa.Column('level', sa.String(length=155), nullable=True))
    # op.drop_column('user_action', 'action_level')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_action', sa.Column('action_level', sa.VARCHAR(length=155), autoincrement=False, nullable=False))
    op.drop_column('action', 'level')
    # ### end Alembic commands ###
